### ISSUE TITLE
request constant power pannah

### ISSUE THREAD

**Issue by glocke01** [MockbaTheBorg/MockbaModular#10]
http://www.cs.cmu.edu/~music/icm-online/readings/panlaws/

![image](https://user-images.githubusercontent.com/12255580/74268848-8e293900-4cd6-11ea-9d63-c48717458e63.png)
![image](https://user-images.githubusercontent.com/12255580/74268853-92555680-4cd6-11ea-8a88-58a542dd59c8.png)

as a switch on pannah or a new cppannah module. possibly I could help implement this (I have written multithreaded C++ for scientific computing purposes) ...

**Comment by MockbaTheBorg** [comment]
This is actually planned for the next release.
I am coincidentally using the "Constant Power Panning" from the same webpage.
It is part of a new free set of tools I will release soon, and I will roll it back to the original free tools as well. (Pannah will get a context menu to select between linear and constant power)
