### ISSUE TITLE
Remove plugin.dll from repository

### ISSUE THREAD

**Issue by cschol** [MockbaTheBorg/MockbaModular#14]
I didnt notice this during the integration review for `v1`, but you have the binary `plugin.dll` committed to the repository.

This is a problem since it increases the repository size unnecessary when the repo is cloned by the Rack build system.

Can you please remove it from the repository and its history? 
A new commit is not enough. You can remove it using https://rtyley.github.io/bfg-repo-cleaner/.

Thanks!

**Comment by MockbaTheBorg** [comment]
Oh good catch.
I will clean it up.
Gotta figure out how to use this BFG on Windows though. :)

Thanks,
Marcelo

**Comment by MockbaTheBorg** [comment]
Should be clean now. 
Can you check?

**Comment by cschol** [comment]
All good. Thanks.
