### ISSUE TITLE
about sheight

### ISSUE THREAD

**Issue by matthleg** [MockbaTheBorg/MockbaModular#15]
Hello, 
first thanks for all your work I love your modules and use them a lot.

I use in every patch sheight and I have two comments:
-You use for each of the eight lines, 1 knob for negative range and 1 knob for positive range, Why not offset and scale? (it would permit more possibilities for ex: from 2 to 4 volts...)
- I would love to have an expander to send trigger for every change of note.
 
Please think about it, 
         have a nice week,
                       all the best.

Matthieu.

**Comment by MockbaTheBorg** [comment]
Hi Matthieu. Sorry for the late late late response.
Covid and Real Life got in the way of me developing the plugins further. Let's see. Maybe I will find time and energy to return to them in the future.
Thanks for the suggestions.

Thanks,
Marcelo.
