### ISSUE TITLE
Does "res mod" affect the resonance value?

### ISSUE THREAD

**Issue by jamshark70** [MockbaTheBorg/MockbaModular#16]
https://github.com/MockbaTheBorg/MockbaModular/blob/master/src/Filtah.cpp#L61

I am perhaps missing something, but it looks like MODR_INPUT is retrieved but then not applied to `res`.

Practical impact is: I connected a MIDI CC (10V) to the resonance mod input and I couldn't hear any difference at any CC value.

**Comment by MockbaTheBorg** [comment]
It should have worked.
Maybe a bad solder joint, or oxidation on the input? 😅
I will check the source code later today and get back to you (traveling at the moment).

**Comment by MockbaTheBorg** [comment]
With this latest commit I should have fixed the problem. Are you building from source?
If so please give it a try.

**Comment by jamshark70** [comment]
I haven't been building from source... no worries, just reporting. Thanks!

**Comment by MockbaTheBorg** [comment]
Okeedokee. I will send the update. 2.0.1 should be out soon.
