### ISSUE TITLE
CZ Series

### ISSUE THREAD

**Issue by blackearth2014** [MockbaTheBorg/MockbaModular#2]
Thanks for developing the CZ series modules. They sound like I remember them.

**Comment by MockbaTheBorg** [comment]
Awesome! Thank you!
Yes, I had a CZ a long time ago, and I can tell you that the waveforms are spot on.
I actually had to study Casio's patent on the Phase Distortion oscillators to develop them.
And had to create them first on Desmos (online graphing calculator) to make sure they look correct.
This is the saw: https://www.desmos.com/calculator/gepe0cxodj
And this is the square: https://www.desmos.com/calculator/yfcyir4rkt
Took me a few days to get everything correct.

Thanks!

**Comment by blackearth2014** [comment]
Bless you!

**Comment by blackearth2014** [comment]
Since your CZ modules are polyphonic. Are they internally synced or not?

**Comment by MockbaTheBorg** [comment]
Not sure what you mean with internally synced, but I want to make one single bigger one which combines all the single waves, and allows you to play them "queued" like the Casio CZ did.
I have already tried doing it but I hit some aliasing issue.
However the waves are all synced to the phase (if this is what you meant by synced), so you can mix them together and they will sound fine.
Stay tuned for the big osc. I will probably charge a few bucks for it, but as you will be my beta tester you get it for free ... lol.

**Comment by blackearth2014** [comment]
Okay Cool. I will still buy it though. I will just budget for it.
