### ISSUE TITLE
Filter development

### ISSUE THREAD

**Issue by blackearth2014** [MockbaTheBorg/MockbaModular#3]
I have noticed on your github manual page that you have developed a moog like filter called Filtah. Nice name by the way. Can you develop a high pass 2/4/6/12/18/24 slope, band pass w/Peak, low pass 2/4/6/12/18/24 slope, and notch filters also as separate modules.

**Comment by MockbaTheBorg** [comment]
Hi ... thanks!
I have been developing for VCV only for a few months. Actually still learning as I go.
I might develop something like this in the future, but at the moment I am focusing on creating a VCV replica of the Behringer Model D.

**Comment by blackearth2014** [comment]
Man!! don't tease or mess with me right now. I can beta test if you want. Hit me up at osbrown@gmail.com.

**Comment by MockbaTheBorg** [comment]
Yeah, will do... I have very little free time (wife and 4 kids, you get the picture), but I will definitely do it.
I do own one, so I have started to draft the panel already ... I will connect with you on gmail.

**Comment by blackearth2014** [comment]
Cool Breeze. I am married with one child. I had her at 41 and Now I am pushing 50.
