### ISSUE TITLE
cool can you make something like this

### ISSUE THREAD

**Issue by ghost** [MockbaTheBorg/MockbaModular#7]
some thing with a big old patchbay built in

**Comment by MockbaTheBorg** [comment]
Been thinking about it, but those still have patents. Could create a
problem for me and VCV.

**Comment by MockbaTheBorg** [comment]
I thought about big patchbay too, but that kinda defeats the purpose of VCV (and modular). It would be eye candy only I think. 
I made my free modules all narrow so people can put them side by side and the "patchbay" would be at the bottom. 
But stay tuned, I still have a few truck up my sleeve.
