### ISSUE TITLE
pannah inverts R output

### ISSUE THREAD

**Issue by glocke01** [MockbaTheBorg/MockbaModular#9]
the R output of pannah is inverted. If this is intended behavior, maybe a switch could be added to turn it off...

**Comment by MockbaTheBorg** [comment]
It should not be inverted.
Which version are you using? I have just tested here and it doesn't seem to be inverted.
![image](https://user-images.githubusercontent.com/16762507/74269007-cfb9e400-4cd6-11ea-88b7-63db182e2248.png)

**Comment by glocke01** [comment]
Mockba version 1.2.0, Rack version 1.1.6, on Ubuntu 18.

**Comment by MockbaTheBorg** [comment]
If you plug it just like the above, does it not look like that?
I cannot run on Linux here, but I have it wired as the above on Windows and it is not inverting.
Can you please try the same and let me know?

**Comment by glocke01** [comment]
![image](https://user-images.githubusercontent.com/12255580/74346763-0e56a980-4d7e-11ea-8ad8-7c4d9a86c4e2.png)

:'(

༼ ༎ຶ ෴ ༎ຶ༽

**Comment by MockbaTheBorg** [comment]
OMG ... how can that be.
I have just released 1.2.1, which has the selection between linear and constant-power.
Is this the one? Can you try that as well?

Thanks!

**Comment by glocke01** [comment]
Just updated and the problem has disappeared for constant power and constant amplitude. Hooray for mysterious bugs that magically solve themselves!

**Comment by MockbaTheBorg** [comment]
Yup ... I always use to say that mysterious bugs that go away for now reason, tend to also come back for no reason.
